### PR TITLE
Allow other modules to check the user agent and change the "is bot" result if desired

### PR DESCRIPTION
**Pull request by kanevbg**
This gives developer an possibility to change easily on per-project basis what is a bot visitor.

### CODE REVIEW

**Comment by kanevbg** [comment]
ah... that is a lib meant to be magento independent ..

**Comment by kanevbg** [comment]
`\Cm\RedisSession\Handler::$_botCheckCallback = [$myCheker, 'userAgentBotCheckCallback'];`
This is example usage. Sets the callback for the bot checking. It should be set before using \Cm\RedisSession\Handler

**Comment by colinmollenhour** [comment]
Thanks!

**Comment by kanevbg** [comment]
Thank u 2!

**Pull request merged**
